package arcane.system;

enum Event {
	KeyDown(k:KeyCode);
	KeyUp(k:Int);
	KeyPress(str:String);

	MouseDown(key:Int, x:Int, y:Int);
	MouseUp(key:Int, x:Int, y:Int);
	MouseEnter;
	MouseLeave;
	MouseMove(dx:Int, dy:Int);
	MouseWheel(delta:Float);
	Resize(w:Int, h:Int);
	FocusGained;
	FocusLost;
}

enum abstract KeyCode(Int) from Int to Int {
	var Unknown;
	var Cancel;
	var Help;
	var Clear;
	var Return;
	var Shift;
	var Control;
	var Alt;
	var Pause;
	var CapsLock;
	var Convert;
	var NonConvert;
	var Accept;
	var ModeChange;
	var PageUp;
	var PageDown;
	var End;
	var Home;
	var Left;
	var Up;
	var Right;
	var Down;
	var Select;
	var Print;
	var Execute;
	var PrintScreen;
	var Colon;
	var SemiColon;
	var LessThan;
	var Equals;
	var GreaterThan;
	var QuestionMark;
	var At;
	var Multiply;
	var Add;
	var Separator;
	var Substract;
	var Decimal;
	var Divide;
	var Meta;
	var AltGr;
	var NumLock;
	var Circumflex;
	var Pipe;
	var Tilde;
	var LeftCurlyBracket;
	var RightCurlyBracket;
	var Insert;
	var Delete;
	var Back;
	var Final;
	var ContextMenu;
	var Sleep;
	var ScrollLock;
	var Windows;
	var Fn;
	var FnLock;
	var Enter;
	var Escape;
	var Backspace;
	var Tab;
	var Space;
	var Exclaim;
	var DoubleQuote;
	var Hash;
	var Percent;
	var Dollar;
	var Ampersand;
	var Quote;
	var LeftParen;
	var RightParen;
	var Asterisk;
	var Plus;
	var Comma;
	var Minus;
	var Period;
	var Slash;
	var LeftBracket;
	var Backslash;
	var RightBracket;
	var Caret;
	var Underscore;
	var Backquote;
	var A;
	var B;
	var C;
	var D;
	var E;
	var F;
	var G;
	var H;
	var I;
	var J;
	var K;
	var L;
	var M;
	var N;
	var O;
	var P;
	var Q;
	var R;
	var S;
	var T;
	var U;
	var V;
	var W;
	var X;
	var Y;
	var Z;
	var Numpad0;
	var Numpad1;
	var Numpad2;
	var Numpad3;
	var Numpad4;
	var Numpad5;
	var Numpad6;
	var Numpad7;
	var Numpad8;
	var Numpad9;
	var Number0;
	var Number1;
	var Number2;
	var Number3;
	var Number4;
	var Number5;
	var Number6;
	var Number7;
	var Number8;
	var Number9;
	var F1;
	var F2;
	var F3;
	var F4;
	var F5;
	var F6;
	var F7;
	var F8;
	var F9;
	var F10;
	var F11;
	var F12;
	var F13;
	var F14;
	var F15;
	var F16;
	var F17;
	var F18;
	var F19;
	var F20;
	var F21;
	var F22;
	var F23;
	var F24;

	public function toString() {
		return switch (this : KeyCode) {
			case Unknown: "Unknown";

			case Cancel: "Cancel";
			case Help: "Help";
			case Clear: "Clear";
			case Return: "Return";
			case Shift: "Shift";
			case Control: "Control";
			case Alt: "Alt";
			case Pause: "Pause";
			case CapsLock: "CapsLock";
			case Convert: "Convert";
			case NonConvert: "NonConvert";
			case Accept: "Accept";
			case ModeChange: "ModeChange";
			case PageUp: "PageUp";
			case PageDown: "PageDown";
			case End: "End";
			case Home: "Home";
			case Left: "Left";
			case Up: "Up";
			case Right: "Right";
			case Down: "Down";
			case Select: "Select";
			case Print: "Print";
			case Execute: "Execute";
			case PrintScreen: "PrintScreen";
			case Colon: "Colon";
			case SemiColon: "SemiColon";
			case LessThan: "LessThan";
			case Equals: "Equals";
			case GreaterThan: "GreaterThan";
			case QuestionMark: "QuestionMark";
			case At: "At";
			case Multiply: "Multiply";
			case Add: "Add";
			case Separator: "Separator";
			case Substract: "Substract";
			case Decimal: "Decimal";
			case Divide: "Divide";
			case Meta: "Meta";
			case AltGr: "AltGr";
			case NumLock: "NumLock";
			case Circumflex: "Circumflex";
			case Pipe: "Pipe";
			case Tilde: "Tilde";
			case LeftCurlyBracket: "LeftCurlyBracket";
			case RightCurlyBracket: "RightCurlyBracket";
			case Insert: "Insert";
			case Delete: "Delete";

			case Enter: "Enter";
			case Escape: "Escape";
			case Backspace: "Backspace";
			case Tab: "Tab";
			case Space: "Space";
			case Exclaim: "Exclaim";
			case DoubleQuote: "DoubleQuote";
			case Hash: "Hash";
			case Percent: "Percent";
			case Dollar: "Dollar";
			case Ampersand: "Ampersand";
			case Quote: "Quote";
			case LeftParen: "LeftParen";
			case RightParen: "RightParen";
			case Asterisk: "Asterisk";
			case Plus: "Plus";
			case Comma: "Comma";
			case Minus: "Minus";
			case Period: "Period";
			case Slash: "Slash";
			case LeftBracket: "LeftBracket";
			case Backslash: "Backslash";
			case RightBracket: "RightBracket";
			case Caret: "Caret";
			case Underscore: "Underscore";
			case Backquote: "Backquote";
			case A: "A";
			case B: "B";
			case C: "C";
			case D: "D";
			case E: "E";
			case F: "F";
			case G: "G";
			case H: "H";
			case I: "I";
			case J: "J";
			case K: "K";
			case L: "L";
			case M: "M";
			case N: "N";
			case O: "O";
			case P: "P";
			case Q: "Q";
			case R: "R";
			case S: "S";
			case T: "T";
			case U: "U";
			case V: "V";
			case W: "W";
			case X: "X";
			case Y: "Y";
			case Z: "Z";
			case Numpad0: "Numpad0";
			case Numpad1: "Numpad1";
			case Numpad2: "Numpad2";
			case Numpad3: "Numpad3";
			case Numpad4: "Numpad4";
			case Numpad5: "Numpad5";
			case Numpad6: "Numpad6";
			case Numpad7: "Numpad7";
			case Numpad8: "Numpad8";
			case Numpad9: "Numpad9";
			case Number0: "Number0";
			case Number1: "Number1";
			case Number2: "Number2";
			case Number3: "Number3";
			case Number4: "Number4";
			case Number5: "Number5";
			case Number6: "Number6";
			case Number7: "Number7";
			case Number8: "Number8";
			case Number9: "Number9";
			case F1: "F1";
			case F2: "F2";
			case F3: "F3";
			case F4: "F4";
			case F5: "F5";
			case F6: "F6";
			case F7: "F7";
			case F8: "F8";
			case F9: "F9";
			case F10: "F10";
			case F11: "F11";
			case F12: "F12";
			case F13: "F13";
			case F14: "F14";
			case F15: "F15";
			case F16: "F16";
			case F17: "F17";
			case F18: "F18";
			case F19: "F19";
			case F20: "F20";
			case F21: "F21";
			case F22: "F22";
			case F23: "F23";
			case F24: "F24";
			case Back: "Back";
			case ContextMenu: "ContextMenu";
			case Final: "Final";
			case ScrollLock: "ScrollLock";
			case Sleep: "Sleep";
			case Windows: "Windows";
			case Fn: "Fn";
			case FnLock: "FnLock";
		}
	}
}
