name: CI

on: [push]

jobs:

  build:
    if: ${{ !contains(join(github.event.commits.*.message),'[skip ci]') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        haxe: [4.1.0,4.1.5,4.2.0]
    steps:
    - uses: krdlab/setup-haxe@master
      with:
          haxe-version: ${{ matrix.haxe }}
    - uses: actions/checkout@v2
    - name: Build
      run: |
        haxelib install tests.hxml
        haxe tests.hxml