name: CI

on: [push]

jobs:
  build:
    if: ${{ !contains(join(github.event.commits.*.message),'[skip ci]') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        haxe: [4.1.0, 4.1.5, 4.2.0,4.2.2,4.2.4, 4.2.5, 4.3.0, 4.3.2, 4.3.4, 4.3.6]
    steps:
    - uses: Apprentice-Alchemist/setup-haxe@use-neko-2.3-for-old-haxe
      with:
          haxe-version: ${{ matrix.haxe }}
    - uses: actions/checkout@v2
    - name: Build
      run: |
        haxelib install libs.hxml --always
    # - name: Run tests
    #   run: |
    #     haxe tests.hxml