name: CI

on: [push]

jobs:

  build:
    if: ${{ !contains(join(github.event.commits.*.message),'[skip ci]') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        haxe: [4.1.4,4.2.0]
    steps:
    - name: Install Haxe
      uses: krdlab/setup-haxe@master
      with:
          haxe-version: ${{ matrix.haxe }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        haxelib git kinc https://github.com/Apprentice-Alchemist/KincHL
        haxe tests.hxml